services:
- type: web
  name: personal-finance-controller-bot
  runtime: docker
  dockerfilePath: ./Dockerfile
  plan: free
  region: oregon
  envVars:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: TZ
    value: America/Sao_Paulo
  - key: RENDER
    value: "true"
  - key: RENDER_EXTERNAL_URL
    value: "https://personal-finance-controller-bot.onrender.com" 